– MySQL

CREATE DATABASE NHSDatabase;

use NHSDatabase;

CREATE TABLE AdminStaff (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	FirstName VARCHAR(40),
LastName VARCHAR(40),
Position VARCHAR(40)
);

CREATE TABLE Country (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(40) NOT NULL
);

CREATE TABLE County (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(40) NOT NULL,
	CountryID INT NOT NULL,
	FOREIGN KEY (CountryID) REFERENCES Country(Id) ON DELETE RESTRICT
	);

CREATE TABLE District (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(40) NOT NULL,
	CountyID INT NOT NULL,
	FOREIGN KEY (CountyID) REFERENCES County(Id) ON DELETE RESTRICT
	);

CREATE TABLE Hospital (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(156) NOT NULL,
	DistrictID INT NOT NULL,
	MaximumCapacity INT NOT NULL,
	FOREIGN KEY (DistrictID) REFERENCES District(Id) ON DELETE RESTRICT
	);

CREATE TABLE MinisterStatement (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	MinisterName VARCHAR(40),
	IssueType VARCHAR(40),
	Statement LONGTEXT,
	CountryId INT NOT NULL,
	FOREIGN KEY (CountryId) REFERENCES Country(Id)
);

CREATE TABLE Patient (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	FirstName VARCHAR(40),
	LastName VARCHAR(40),
	DistrictId INT NOT NULL,
	FOREIGN KEY (DistrictId) REFERENCES District(Id),
	Postcode VARCHAR(10),
	PhoneNo VarChar(20),
	Address VarChar(50),
	Gender VarChar(10)
);

CREATE TABLE PatientRecord (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	PatientId INT NOT NULL,
	FOREIGN KEY (PatientId) REFERENCES Patient(Id),
	DateOfAppointment DATE,
	HospitalId INT NOT NULL,
	FOREIGN KEY (HospitalId) REFERENCES Hospital(Id),
	Reason VARCHAR(255),
	Notes VARCHAR(255),
	Tests VARCHAR(255),
	Admitted BOOLEAN
);

CREATE TABLE Appointment (
Id INT AUTO_INCREMENT PRIMARY KEY, 
PatientId INT NOT NULL, 
HospitalId INT NOT NULL, 
Date DATE NOT NULL,
Reason VARCHAR(255), 
FOREIGN KEY (PatientId) REFERENCES Patient(Id) ON DELETE CASCADE, FOREIGN KEY (HospitalId) REFERENCES Hospital(Id) ON DELETE CASCADE
);

CREATE TABLE WaitingListAppointment(
	Id INT AUTO_INCREMENT PRIMARY KEY,	
WaitingListId INT, 
AppointmentId INT NOT NULL UNIQUE, 
FOREIGN KEY (AppointmentId) REFERENCES Appointment(Id) ON DELETE CASCADE
);

CREATE TABLE DirectAppointment(
	Id INT AUTO_INCREMENT PRIMARY KEY,
	AppointmentId INT NOT NULL UNIQUE,
	adminStaffId INT NOT NULL,
	FOREIGN KEY (AppointmentId) REFERENCES Appointment(Id) ON DELETE CASCADE,
	FOREIGN KEY (adminStaffId) REFERENCES AdminStaff(Id) ON DELETE RESTRICT
);

CREATE TABLE WaitingList (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	PatientId INT NOT NULL,
	TreatmentType VARCHAR(40),
	DateOfEntry DATE,
	WLAppointmentId INT,
	FOREIGN KEY (WLAppointmentId) REFERENCES WaitingListAppointment(Id) ON DELETE CASCADE,
	FOREIGN KEY (PatientId) REFERENCES Patient(Id)
);

ALTER TABLE WaitingListAppointment ADD CONSTRAINT fk_Name FOREIGN KEY (WaitingListId) REFERENCES WaitingList(Id) ON DELETE RESTRICT;
